theme: jekyll-theme-leap-day
title: Python para engenharia
locale: pt-BR
description: Site de apoio do curso online de Python para a engenharia com aplicações
relative_links:
  enabled: true
  collections: true
include:
  - README.md
